server:
  port: 8080


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console


#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'

management:
  endpoints:
    web:
      exposure:
        include: beans, metrics, info, health, loggers, readiness
  endpoint:
    health:
      show-details: always
#  endpoint:
#    loggers:
#      enabled: false